const fs = require('fs-extra')
const path = require('path')

const traverseDirectory = require('./traverseDirectory')
const diffFolderStructure = require('./diffFolderStructure')
const generatePatches = require('./generatePatches')
const { copyToFolder, doPatch } = require('./utils')

/**
 * @typedef {Object.<string, { filename: string; md5: string; size: number }>} FileInfo
 */

/**
 * @typedef {Object} DiffInfo
 * @property {FileInfo} added
 * @property {FileInfo} deleted
 * @property {FileInfo} modified
 * @property {FileInfo} unchanged
 */

/**
 * Description
 * @param {string} folderA path of folderA
 * @param {string} folderB path of folderB
 * @param {string} folderPatch path of patchPackage
 */
async function generatePatchPackage({ folderA, folderB, folderPatch, doDiffThreshold = 1024 * 500 }) {
  /** @type {FileInfo} */
  const folderAFileInfo = await traverseDirectory(folderA)
  /** @type {FileInfo} */
  const folderBFileInfo = await traverseDirectory(folderB)
  /** @type {DiffInfo} */
  const diffJson = diffFolderStructure(folderAFileInfo, folderBFileInfo)

  const diffJsonPath = path.join(folderPatch, 'diff.json')

  await fs.ensureDir(folderPatch)
  await fs.emptyDir(folderPatch)
  await fs.writeFile(diffJsonPath, JSON.stringify(diffJson, null, 2), 'utf-8')

  const { added, modified } = diffJson
  // copy all added files into folderPatch
  Object.keys(added).forEach(async (filePath) => {
    await copyToFolder(folderB, filePath, path.join(folderPatch, 'new_version'))
  })

  // copy all modified files which is smaller than doDiffThreshold into folderPatch
  Object.keys(modified).forEach(async (filePath) => {
    if (modified[filePath].size > doDiffThreshold) return
    await copyToFolder(folderB, filePath, path.join(folderPatch, 'new_version'))
  })

  await generatePatches({
    folderA,
    folderB,
    diffJson,
    doDiffThreshold,
    folderPatch,
  })
}

async function generateNewVersionPackage({ folderA, folderPatch, folderNew }) {
  // 1. init folderNew folder
  fs.removeSync(folderNew)
  fs.mkdirSync(folderNew)

  // 2. copy all unchanged files into folderNew folder
  const diffJson = JSON.parse(fs.readFileSync(path.join(folderPatch, 'diff.json')))
  const { unchanged, modified } = diffJson
  
  Object.keys(unchanged).forEach(filePath => {
    copyToFolder(folderA, filePath, folderNew)
  })

  // 3. use bsdiff to patch files, or just copy to folderNew
  const doPatchPromises = []

  Object.keys(modified).forEach(filePath => {
    const newFileInfo = modified[filePath]
    const { filename } = newFileInfo
    const patchFileName = `${filename}.patch`
    const existsPatchFiles = fs.readdirSync(folderPatch)
    // These files should be generated by bsdiff.patch
    if (existsPatchFiles.includes(patchFileName)) {
      const originFilePath = path.join(folderA, filePath)
      const newFilePath = path.join(folderNew, filePath)
      
      fs.ensureDirSync(path.dirname(newFilePath))
      const doPatchPromise = doPatch(originFilePath, newFilePath, path.join(folderPatch, patchFileName))
      doPatchPromises.push(doPatchPromise)
    }
  })

  console.time('\nFinish all patch operation')
  const res = await Promise.all(doPatchPromises)
  console.timeEnd('\nFinish all patch operation')

  await fs.copy(path.join(folderPatch, 'new_version'), folderNew)

  return res
}

exports.generatePatchPackage = generatePatchPackage
exports.generateNewVersionPackage = generateNewVersionPackage
